import type { Metadata } from "next";
import localFont from "next/font/local"
import "./globals.css";
import AppProvider from "./provider";

const generalSans = localFont({
  src: '../public/fonts/GeneralSans-Regular.woff2',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${generalSans.className} antialiased`}
      >
        <AppProvider>
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
